{{- if and .Values.apiserver.e2b.enabled .Values.apiserver.e2b.envdSecret.value }}
apiVersion: v1
kind: Secret
metadata:
  name: sandbox-e2b-envd-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sandbox-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.apiserver.e2b.envdSecret.key }}: {{ .Values.apiserver.e2b.envdSecret.value | quote }}
{{- end }}
