//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForkedSandbox) DeepCopyInto(out *ForkedSandbox) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForkedSandbox.
func (in *ForkedSandbox) DeepCopy() *ForkedSandbox {
	if in == nil {
		return nil
	}
	out := new(ForkedSandbox)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InventoryEntry) DeepCopyInto(out *InventoryEntry) {
	*out = *in
	if in.Deadline != nil {
		in, out := &in.Deadline, &out.Deadline
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InventoryEntry.
func (in *InventoryEntry) DeepCopy() *InventoryEntry {
	if in == nil {
		return nil
	}
	out := new(InventoryEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeInventory) DeepCopyInto(out *NodeInventory) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]InventoryEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Pools != nil {
		in, out := &in.Pools, &out.Pools
		*out = make([]PoolCapacity, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeInventory.
func (in *NodeInventory) DeepCopy() *NodeInventory {
	if in == nil {
		return nil
	}
	out := new(NodeInventory)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeInventory) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeInventoryList) DeepCopyInto(out *NodeInventoryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeInventory, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeInventoryList.
func (in *NodeInventoryList) DeepCopy() *NodeInventoryList {
	if in == nil {
		return nil
	}
	out := new(NodeInventoryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeInventoryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PoolCapacity) DeepCopyInto(out *PoolCapacity) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PoolCapacity.
func (in *PoolCapacity) DeepCopy() *PoolCapacity {
	if in == nil {
		return nil
	}
	out := new(PoolCapacity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxForkOptions) DeepCopyInto(out *SandboxForkOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxForkOptions.
func (in *SandboxForkOptions) DeepCopy() *SandboxForkOptions {
	if in == nil {
		return nil
	}
	out := new(SandboxForkOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxForkOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxForkResult) DeepCopyInto(out *SandboxForkResult) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	if in.Children != nil {
		in, out := &in.Children, &out.Children
		*out = make([]ForkedSandbox, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxForkResult.
func (in *SandboxForkResult) DeepCopy() *SandboxForkResult {
	if in == nil {
		return nil
	}
	out := new(SandboxForkResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxForkResult) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxPauseOptions) DeepCopyInto(out *SandboxPauseOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxPauseOptions.
func (in *SandboxPauseOptions) DeepCopy() *SandboxPauseOptions {
	if in == nil {
		return nil
	}
	out := new(SandboxPauseOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxPauseOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxResumeOptions) DeepCopyInto(out *SandboxResumeOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxResumeOptions.
func (in *SandboxResumeOptions) DeepCopy() *SandboxResumeOptions {
	if in == nil {
		return nil
	}
	out := new(SandboxResumeOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxResumeOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxSnapshotOptions) DeepCopyInto(out *SandboxSnapshotOptions) {
	*out = *in
	out.TypeMeta = in.TypeMeta
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxSnapshotOptions.
func (in *SandboxSnapshotOptions) DeepCopy() *SandboxSnapshotOptions {
	if in == nil {
		return nil
	}
	out := new(SandboxSnapshotOptions)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxSnapshotOptions) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SandboxSnapshotResult) DeepCopyInto(out *SandboxSnapshotResult) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.CreationTimestamp.DeepCopyInto(&out.CreationTimestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SandboxSnapshotResult.
func (in *SandboxSnapshotResult) DeepCopy() *SandboxSnapshotResult {
	if in == nil {
		return nil
	}
	out := new(SandboxSnapshotResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SandboxSnapshotResult) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
