name: build

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'LICENSE'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
          - goos: linux
            goarch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v7.0.0
        with:
          go-version-file: 'go.mod'

      - name: Download dependencies
        run: go mod download

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: make build

      - name: Upload binary artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: sandbox-operator-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            bin/sandbox-apiserver
            bin/sandbox-envd-proxy
          retention-days: 30
